apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: homework
  name: kubernetes-controllers
  labels:
    homework: kubernetes-controllers
spec:
  replicas: 2
  selector:
    matchLabels:
      homework: kubernetes-controllers
  template:
    metadata:
      labels:
        homework: kubernetes-controllers
    spec:
      initContainers:
        - name: init
          image: busybox:1.36 
          command: ["/bin/sh", "-c"]
          args:
            - "echo 'Homework 2' > /init/index.html"
          volumeMounts:
            - name: webdir
              mountPath: /init  
      containers:
      - name: web-server
        image: nginx:1.27.5
        ports:
        - containerPort: 8000
        command: ["/bin/sh", "-c"]
        args:
          - "sed -i 's/listen       80;/listen 8000;/g' /etc/nginx/conf.d/default.conf; sed -i 's|root   /usr/share/nginx/html;|root /homework;|g' /etc/nginx/conf.d/default.conf; exec nginx -g 'daemon off;'"
        volumeMounts:
        - name: webdir
          mountPath: /homework
        lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -f /homework/index.html"]
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5  # Задержка перед первой проверкой (секунды)
          periodSeconds: 10       # Интервал между проверками (секунды)
          timeoutSeconds: 2       # Таймаут ожидания ответа (секунды)
          successThreshold: 1    # Количество успешных проверок для "готовности"
          failureThreshold: 3     # Количество неудачных проверок для "неготовности"
      volumes:
        - name: webdir
          emptyDir: {}
  
