apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: homework
data:
  default.conf: |
    server {
      listen 8000;
      server_name localhost;

      location / {
          root /homework;
          index index.html index.htm;
      }

      # Редирект с /homepage на /
      location = /homepage {
          return 301 /;
      }

      error_page 500 502 503 504 /50x.html;
      location = /50x.html {
          root /homework;
      }
    }

