apiVersion: v1
kind: Pod
metadata:
  namespace: homework
  name: kubernetes-intro
spec:
  initContainers:
    - name: init
      image: busybox:1.36 
      command: ["/bin/sh", "-c"]
      args:
        - "echo 'Homework 1' > /init/index.html"
      volumeMounts:
        - name: webdir
          mountPath: /init  
  containers:
  - name: web-server
    image: nginx:1.27.5
    ports:
    - containerPort: 8000
    command: ["/bin/sh", "-c"]
    args:
      - "sed -i 's/listen       80;/listen 8000;/g' /etc/nginx/conf.d/default.conf; sed -i 's|root   /usr/share/nginx/html;|root /homework;|g' /etc/nginx/conf.d/default.conf; exec nginx -g 'daemon off;'"
    volumeMounts:
    - name: webdir
      mountPath: /homework
  volumes:
    - name: webdir
      emptyDir: {}
  