apiVersion: v1
kind: Secret
metadata:
  name: cd-token-expiring
  namespace: homework
  annotations:
    kubernetes.io/service-account.name: cd
    kubernetes.io/service-account.expiration: "86400"
type: kubernetes.io/service-account-token
 