apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
data:
  {{- toYaml .Values.configmap.data | nindent 2 }}
