apiVersion: v1
kind: Service
metadata:
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  name: {{ .Values.service.name }}
spec:
  selector:
    {{ .Values.global.homeworkLabel }}: {{ .Values.deployment.name }}
  ports:
    - name: http-access-port
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
